#根路径(省略时继续父进程)。
#--root-path
#/myroot/

#工作路径(省略时继续父进程)。
#--work-path
#/myworkhome/

#环境变量(覆盖)。
--env-overwrite
MYENV1=sample

#环境变量(覆盖)。
--env-append
MYENV2=sample

#命令行
--cmd
tree /usr/

#日志文件。
--log-file

#日志片段大小(MB)。
--log-segment-size
10

#日志片段最大数量。
--log-segment-max
10

#重启间隔(秒),默认：5
--restart-interval
5






